### ISSUE TITLE
Customize ATIS freaks

### ISSUE THREAD

**Issue by etcher-be** [132nd-vWing/ESST#104]
Config file should allow for a list of icao, with ATIS freak.

Standard format:

```yaml
icao:
  xxxx:
    atis:
      123.00
```
